#pragma checksum "..\..\..\..\View\RecentFileButton.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "55ADA057D750AC242FF2C857E4B0173B35CCB88A"
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using Syncfusion.UI.Xaml.Diagram.Utility;
using System;
using System.Collections;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using syncfusion.brainstormingdiagram.wpf.Utility;
using syncfusion.brainstormingdiagram.wpf.View;
using syncfusion.brainstormingdiagram.wpf.ViewModel;


namespace syncfusion.brainstormingdiagram.wpf.View {
    
    
    /// <summary>
    /// RecentFileButton
    /// </summary>
    public partial class RecentFileButton : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 1 "..\..\..\..\View\RecentFileButton.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal syncfusion.brainstormingdiagram.wpf.View.RecentFileButton recentFileControl;
        
        #line default
        #line hidden
        
        
        #line 49 "..\..\..\..\View\RecentFileButton.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lblFileName;
        
        #line default
        #line hidden
        
        
        #line 53 "..\..\..\..\View\RecentFileButton.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtFileName;
        
        #line default
        #line hidden
        
        
        #line 59 "..\..\..\..\View\RecentFileButton.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid PART_Menu;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "6.0.3.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/syncfusion.brainstormingdiagram.wpf;component/view/recentfilebutton.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\View\RecentFileButton.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "6.0.3.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.recentFileControl = ((syncfusion.brainstormingdiagram.wpf.View.RecentFileButton)(target));
            return;
            case 2:
            this.lblFileName = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 3:
            this.txtFileName = ((System.Windows.Controls.TextBox)(target));
            return;
            case 4:
            this.PART_Menu = ((System.Windows.Controls.Grid)(target));
            return;
            case 5:
            
            #line 75 "..\..\..\..\View\RecentFileButton.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.PART_Menu_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            
            #line 76 "..\..\..\..\View\RecentFileButton.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.PART_Menu_Click);
            
            #line default
            #line hidden
            return;
            case 7:
            
            #line 77 "..\..\..\..\View\RecentFileButton.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.PART_Menu_Click);
            
            #line default
            #line hidden
            return;
            case 8:
            
            #line 78 "..\..\..\..\View\RecentFileButton.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.PART_Menu_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

