#pragma checksum "..\..\..\..\Views\ImportNestedCollection.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "C5DA9A06D866B4ED4CABDE1499AF9D7E63D5E11D"
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using syncfusion.demoscommon.wpf;


namespace syncfusion.xlsiodemos.wpf {
    
    
    /// <summary>
    /// ImportNestedCollection
    /// </summary>
    public partial class ImportNestedCollection : syncfusion.demoscommon.wpf.DemoControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 13 "..\..\..\..\Views\ImportNestedCollection.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid DataBinding;
        
        #line default
        #line hidden
        
        
        #line 36 "..\..\..\..\Views\ImportNestedCollection.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock textBlock1;
        
        #line default
        #line hidden
        
        
        #line 37 "..\..\..\..\Views\ImportNestedCollection.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock textBlock2;
        
        #line default
        #line hidden
        
        
        #line 38 "..\..\..\..\Views\ImportNestedCollection.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.GroupBox groupBox1;
        
        #line default
        #line hidden
        
        
        #line 52 "..\..\..\..\Views\ImportNestedCollection.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label label4;
        
        #line default
        #line hidden
        
        
        #line 53 "..\..\..\..\Views\ImportNestedCollection.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmbLayout;
        
        #line default
        #line hidden
        
        
        #line 54 "..\..\..\..\Views\ImportNestedCollection.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox checkBox;
        
        #line default
        #line hidden
        
        
        #line 55 "..\..\..\..\Views\ImportNestedCollection.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.GroupBox groupBox2;
        
        #line default
        #line hidden
        
        
        #line 65 "..\..\..\..\Views\ImportNestedCollection.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rdbExpand;
        
        #line default
        #line hidden
        
        
        #line 66 "..\..\..\..\Views\ImportNestedCollection.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rdbCollapse;
        
        #line default
        #line hidden
        
        
        #line 67 "..\..\..\..\Views\ImportNestedCollection.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox tbLevel;
        
        #line default
        #line hidden
        
        
        #line 72 "..\..\..\..\Views\ImportNestedCollection.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnCreate;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "6.0.3.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/syncfusion.xlsiodemos.wpf;component/views/importnestedcollection.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\Views\ImportNestedCollection.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "6.0.3.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.DataBinding = ((System.Windows.Controls.Grid)(target));
            return;
            case 2:
            this.textBlock1 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 3:
            this.textBlock2 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            this.groupBox1 = ((System.Windows.Controls.GroupBox)(target));
            return;
            case 5:
            this.label4 = ((System.Windows.Controls.Label)(target));
            return;
            case 6:
            this.cmbLayout = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 7:
            this.checkBox = ((System.Windows.Controls.CheckBox)(target));
            
            #line 54 "..\..\..\..\Views\ImportNestedCollection.xaml"
            this.checkBox.Checked += new System.Windows.RoutedEventHandler(this.checkBox_Changed);
            
            #line default
            #line hidden
            
            #line 54 "..\..\..\..\Views\ImportNestedCollection.xaml"
            this.checkBox.Unchecked += new System.Windows.RoutedEventHandler(this.checkBox_Changed);
            
            #line default
            #line hidden
            return;
            case 8:
            this.groupBox2 = ((System.Windows.Controls.GroupBox)(target));
            return;
            case 9:
            this.rdbExpand = ((System.Windows.Controls.RadioButton)(target));
            
            #line 65 "..\..\..\..\Views\ImportNestedCollection.xaml"
            this.rdbExpand.Checked += new System.Windows.RoutedEventHandler(this.expandCollapse_Checked);
            
            #line default
            #line hidden
            return;
            case 10:
            this.rdbCollapse = ((System.Windows.Controls.RadioButton)(target));
            
            #line 66 "..\..\..\..\Views\ImportNestedCollection.xaml"
            this.rdbCollapse.Checked += new System.Windows.RoutedEventHandler(this.expandCollapse_Checked);
            
            #line default
            #line hidden
            return;
            case 11:
            this.tbLevel = ((System.Windows.Controls.TextBox)(target));
            
            #line 67 "..\..\..\..\Views\ImportNestedCollection.xaml"
            this.tbLevel.PreviewTextInput += new System.Windows.Input.TextCompositionEventHandler(this.numberValidation_TextBox);
            
            #line default
            #line hidden
            return;
            case 12:
            this.btnCreate = ((System.Windows.Controls.Button)(target));
            
            #line 72 "..\..\..\..\Views\ImportNestedCollection.xaml"
            this.btnCreate.Click += new System.Windows.RoutedEventHandler(this.btnCreate_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

