#pragma checksum "..\..\..\..\Views\TemplateMarker.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "798D7E722D7A5D77C627E577B30A8508CA2B946C"
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using syncfusion.demoscommon.wpf;


namespace syncfusion.xlsiodemos.wpf {
    
    
    /// <summary>
    /// TemplateMarker
    /// </summary>
    public partial class TemplateMarker : syncfusion.demoscommon.wpf.DemoControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 13 "..\..\..\..\Views\TemplateMarker.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid DataBinding;
        
        #line default
        #line hidden
        
        
        #line 39 "..\..\..\..\Views\TemplateMarker.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock textBlock1;
        
        #line default
        #line hidden
        
        
        #line 40 "..\..\..\..\Views\TemplateMarker.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock textBlock2;
        
        #line default
        #line hidden
        
        
        #line 41 "..\..\..\..\Views\TemplateMarker.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock textBlock3;
        
        #line default
        #line hidden
        
        
        #line 43 "..\..\..\..\Views\TemplateMarker.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel stackPnlOptions;
        
        #line default
        #line hidden
        
        
        #line 44 "..\..\..\..\Views\TemplateMarker.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock importOptions;
        
        #line default
        #line hidden
        
        
        #line 45 "..\..\..\..\Views\TemplateMarker.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rdbtnDataTable;
        
        #line default
        #line hidden
        
        
        #line 46 "..\..\..\..\Views\TemplateMarker.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rdbtnCLRObjects;
        
        #line default
        #line hidden
        
        
        #line 48 "..\..\..\..\Views\TemplateMarker.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock textBlock4;
        
        #line default
        #line hidden
        
        
        #line 50 "..\..\..\..\Views\TemplateMarker.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock imageOptions;
        
        #line default
        #line hidden
        
        
        #line 51 "..\..\..\..\Views\TemplateMarker.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock textBlock5;
        
        #line default
        #line hidden
        
        
        #line 52 "..\..\..\..\Views\TemplateMarker.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rdbtnImage;
        
        #line default
        #line hidden
        
        
        #line 53 "..\..\..\..\Views\TemplateMarker.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rdbtnSize;
        
        #line default
        #line hidden
        
        
        #line 54 "..\..\..\..\Views\TemplateMarker.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rdbtnPosition;
        
        #line default
        #line hidden
        
        
        #line 55 "..\..\..\..\Views\TemplateMarker.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rdbtnSizeAndPosition;
        
        #line default
        #line hidden
        
        
        #line 56 "..\..\..\..\Views\TemplateMarker.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rdbtnFitToCell;
        
        #line default
        #line hidden
        
        
        #line 58 "..\..\..\..\Views\TemplateMarker.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock textBlock6;
        
        #line default
        #line hidden
        
        
        #line 59 "..\..\..\..\Views\TemplateMarker.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnInput;
        
        #line default
        #line hidden
        
        
        #line 60 "..\..\..\..\Views\TemplateMarker.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnCreate;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "6.0.3.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/syncfusion.xlsiodemos.wpf;component/views/templatemarker.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\Views\TemplateMarker.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "6.0.3.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.DataBinding = ((System.Windows.Controls.Grid)(target));
            return;
            case 2:
            this.textBlock1 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 3:
            this.textBlock2 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            this.textBlock3 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 5:
            this.stackPnlOptions = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 6:
            this.importOptions = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 7:
            this.rdbtnDataTable = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 8:
            this.rdbtnCLRObjects = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 9:
            this.textBlock4 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 10:
            this.imageOptions = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 11:
            this.textBlock5 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 12:
            this.rdbtnImage = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 13:
            this.rdbtnSize = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 14:
            this.rdbtnPosition = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 15:
            this.rdbtnSizeAndPosition = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 16:
            this.rdbtnFitToCell = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 17:
            this.textBlock6 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 18:
            this.btnInput = ((System.Windows.Controls.Button)(target));
            
            #line 59 "..\..\..\..\Views\TemplateMarker.xaml"
            this.btnInput.Click += new System.Windows.RoutedEventHandler(this.btnInput_Click);
            
            #line default
            #line hidden
            return;
            case 19:
            this.btnCreate = ((System.Windows.Controls.Button)(target));
            
            #line 60 "..\..\..\..\Views\TemplateMarker.xaml"
            this.btnCreate.Click += new System.Windows.RoutedEventHandler(this.btnCreate_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

